version: '3'

services:
  dashboardDB:
    image: postgres:15.3
    container_name: dashboardDB
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dashboardDB
    volumes:
      - ./postgres:/var/lib/postgresql/data
